---
# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

rules:
  line-length: disable

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  comments:
    min-spaces-from-content: 1

  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
    check-keys: true

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  document-start:
    present: true
